export const ImageAssets = {
    loginPromoImg: require('../../assets/images/loginPromoImg.png'),
    authUserImg: require('../../assets/images/authUserImg.png'),
    authBellImg: require('../../assets/images/authBellImg.png'),
    googleIcon: require('../../assets/images/googleIcon.png'),
    passkeyIcon: require('../../assets/images/passkeyIcon.png'),
    authBackIcon: require('../../assets/images/authBackIcon.png'),
    verifyEmailImg: require('../../assets/images/verifyEmailImg.png'),
    setPasswordImg: require('../../assets/images/setPasswordImg.png'),
    verifyPasskeyImg: require('../../assets/images/verifyPasskeyImg.png'),
    lock: require('../../assets/images/lock.png'),
    splash: require('../../assets/images/splash.png'),
    EarnIcon: require('../../assets/images/EarnIcon.png'),
    MarketIcon: require('../../assets/images/MarketIcon.png'),
    TradeIcon: require('../../assets/images/TradeIcon.png'),
    AssetsIcon: require('../../assets/images/AssetsIcon.png'),
    landingpagedemo: require('../../assets/images/landingpagedemo.png'),
    gridIcon: require('../../assets/images/gridIcon.png'),
    bellIcon: require('../../assets/images/bellIcon.png'),
    giftIcon: require('../../assets/images/giftIcon.png'),
    verifyIdentity: require('../../assets/images/verifyIdentity.png'),
    walletIcon: require('../../assets/images/walletIcon.png'),
    swapIcon: require('../../assets/images/swapIcon.png'),
    moreIcon: require('../../assets/images/moreIcon.png'),
    spotIcon: require('../../assets/images/spotIcon.png'),
    marginIcon: require('../../assets/images/marginIcon.png'),
    event1: require('../../assets/images/event1.png'),
    easyEarn: require('../../assets/images/easyEarn.png'),
    tokenSplash: require('../../assets/images/tokenSplash.png'),
    easyEarnPromo: require('../../assets/images/easyEarnPromo.png'),
    earnCoin: require('../../assets/images/earnCoin.png'),
    stakingHomeIcon: require('../../assets/images/stakingHomeIcon.png'),
    newsImg: require('../../assets/images/newsImg.png'),
    verifyKycModalImg: require('../../assets/images/verifyKycModalImg.png'),
    FingerprintIcon: require('../../assets/images/FingerprintIcon.png'),
    PassportIcon: require('../../assets/images/PassportIcon.png'),
    LicenceIcon: require('../../assets/images/LicenceIcon.png'),
    IDCardIcon: require('../../assets/images/IDCardIcon.png'),
    docCheckImg: require('../../assets/images/docCheckImg.png'),
    ShieldCheckIcon: require('../../assets/images/ShieldCheckIcon.png'),
    IDCardCheckIcon: require('../../assets/images/IDCardCheckIcon.png'),
    CameraCheckIcon: require('../../assets/images/CameraCheckIcon.png'),
    faceVerification: require('../../assets/images/faceVerification.png'),
    faceVeificationUser: require('../../assets/images/faceVeificationUser.png'),
    verifyingImg: require('../../assets/images/verifyingImg.png'),
    verification_reject: require('../../assets/images/verification_reject.png'),
    verification_pending: require('../../assets/images/verification_pending.png'),
    verification_success: require('../../assets/images/verification_success.png'),






}